package edu.csupomona.cs.cs411.project1.lexer;

import java.io.Reader;

/**
 * This class represents a lexical analyzer which can be used to read a byte
 * stream and generate a {@link TokenStream}.
 *
 * @author Collin Smith <collinsmith@csupomona.edu>
 * @param <E> type of the tokens to generate
 */
public interface Lexer<E> {
	/**
	 * Returns a stream of tokens generated by this Lexer.
	 *
	 * @param r the reader to generate tokens from
	 * @return stream of tokens generated
	 */
	TokenStream lex(Reader r);

	/**
	 * Returns the next token found in the stream.
	 *
	 * @param r the reader to generate the token from
	 * @return the next token found or {@code null} if invalid
	 */
	E next(Reader r);
}
